"""create mpk stop times

Revision ID: 0c9d90c7c7fd
Revises: 7f53ad978a45
Create Date: 2026-10-06 17:43:04.544227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c9d90c7c7fd'
down_revision: Union[str, Sequence[str], None] = '7f53ad978a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpk_stop_times',
    sa.Column('source', sa.String(length=1), nullable=False),
    sa.Column('trip_id', sa.Text(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Text(), nullable=False),
    sa.Column('arrival_seconds', sa.Integer(), nullable=True),
    sa.Column('departure_seconds', sa.Integer(), nullable=True),
    sa.Column('stop_headsign', sa.Text(), server_default='', nullable=False),
    sa.Column('pickup_type', sa.Integer(), server_default='0', nullable=False),
    sa.Column('drop_off_type', sa.Integer(), server_default='0', nullable=False),
    sa.Column('timepoint', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint("source IN ('A', 'T')", name='ck_mpk_stop_times_source'),
    sa.CheckConstraint('arrival_seconds >= 0', name='ck_mpk_stop_times_arrival'),
    sa.CheckConstraint('departure_seconds >= 0', name='ck_mpk_stop_times_departure'),
    sa.CheckConstraint('departure_seconds >= arrival_seconds', name='ck_mpk_stop_time_order'),
    sa.CheckConstraint('pickup_type IN (0, 1, 2, 3)', name='ck_mpk_stop_times_drop_off'),
    sa.CheckConstraint('stop_sequence >= 0', name='ck_mpk_stop_times_sequence'),
    sa.CheckConstraint('timepoint IN (0, 1)', name='ck_mpk_stop_times_timepoint'),
    sa.ForeignKeyConstraint(['source', 'trip_id'], ['mpk_trips.source', 'mpk_trips.trip_id'], name='fk_mpk_stop_times_stop'),
    sa.PrimaryKeyConstraint('source', 'trip_id', 'stop_sequence')
    )
    op.create_index('ix_mpk_stop_times_stop_departure', 'mpk_stop_times', ['source', 'stop_id', 'departure_seconds'], unique=False)
    # ### end Alembic commands ###
    op.execute(
        "ALTER TABLE public.mpk_stop_times ENABLE ROW LEVEL SECURITY"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mpk_stop_times_stop_departure', table_name='mpk_stop_times')
    op.drop_table('mpk_stop_times')
    # ### end Alembic commands ###
