"""create mpk trips

Revision ID: 625b7d21a28a
Revises: 8e84b3437ce8
Create Date: 2026-10-02 08:41:20.591662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625b7d21a28a'
down_revision: Union[str, Sequence[str], None] = '8e84b3437ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpk_trips',
    sa.Column('source', sa.String(length=1), nullable=False),
    sa.Column('trip_id', sa.Text(), nullable=False),
    sa.Column('route_id', sa.Text(), nullable=False),
    sa.Column('service_id', sa.Text(), nullable=False),
    sa.Column('headsign', sa.Text(), server_default='', nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("source IN ('A', 'T')", name='ck_mpk_trips_source'),
    sa.CheckConstraint('direction_id IS NULL OR direction_id IN (0, 1)', name='ck_mpk_trips_direction'),
    sa.ForeignKeyConstraint(['source', 'route_id'], ['mpk_routes.source', 'mpk_routes.route_id'], name='fk_mpk_trips_route'),
    sa.PrimaryKeyConstraint('source', 'trip_id')
    )
    op.create_index('ix_mpk_trips_source_route_service', 'mpk_trips', ['source', 'route_id', 'service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mpk_trips_source_route_service', table_name='mpk_trips')
    op.drop_table('mpk_trips')
    # ### end Alembic commands ###
