"""create mpk calendars

Revision ID: 7f53ad978a45
Revises: 8e402c799b0c
Create Date: 2026-10-06 15:28:41.135498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f53ad978a45'
down_revision: Union[str, Sequence[str], None] = '8e402c799b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpk_calendar_dates',
    sa.Column('source', sa.String(length=1), nullable=False),
    sa.Column('service_id', sa.Text(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('exception_type', sa.Integer(), nullable=False),
    sa.CheckConstraint("source IN ('A', 'T')", name='ck_mpk_calendar_dates_source'),
    sa.CheckConstraint('exception_type IN (1,2)', name='ck_mpk_calendar_dates_type'),
    sa.PrimaryKeyConstraint('source', 'service_id', 'service_date')
    )
    op.create_table('mpk_calendars',
    sa.Column('source', sa.String(length=1), nullable=False),
    sa.Column('service_id', sa.Text(), nullable=False),
    sa.Column('monday', sa.Boolean(), nullable=False),
    sa.Column('tuesday', sa.Boolean(), nullable=False),
    sa.Column('wednesday', sa.Boolean(), nullable=False),
    sa.Column('thursday', sa.Boolean(), nullable=False),
    sa.Column('friday', sa.Boolean(), nullable=False),
    sa.Column('saturday', sa.Boolean(), nullable=False),
    sa.Column('sunday', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.CheckConstraint("source IN ('A', 'T')", name='ck_mpk_calendars_source'),
    sa.CheckConstraint('end_date >= start_date', name='ck_mpk_calendars_date_range'),
    sa.PrimaryKeyConstraint('source', 'service_id')
    )
    # ### end Alembic commands ###
    op.execute(
        "ALTER TABLE public.mpk_calendars ENABLE ROW LEVEL SECURITY"
    )
    op.execute(
        "ALTER TABLE public.mpk_calendar_dates ENABLE ROW LEVEL SECURITY"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mpk_calendars')
    op.drop_table('mpk_calendar_dates')
    # ### end Alembic commands ###
