"""create mpk trips

Revision ID: 8e402c799b0c
Revises: 8e84b3437ce8
Create Date: 2026-10-02 08:35:03.036804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e402c799b0c'
down_revision: Union[str, Sequence[str], None] = '8e84b3437ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE public.mpk_trips ENABLE ROW LEVEL SECURITY")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
