"""create mpk routes

Revision ID: 8e84b3437ce8
Revises: f7fb62616c4c
Create Date: 2026-10-01 08:40:29.221236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e84b3437ce8'
down_revision: Union[str, Sequence[str], None] = 'f7fb62616c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpk_routes',
    sa.Column('source', sa.String(length=1), nullable=False),
    sa.Column('route_id', sa.Text(), nullable=False),
    sa.Column('short_name', sa.Text(), server_default='', nullable=False),
    sa.Column('long_name', sa.Text(), server_default='', nullable=False),
    sa.Column('route_type', sa.Integer(), nullable=False),
    sa.CheckConstraint("source IN ('A', 'T')", name='ck_mpk_routes_source'),
    sa.CheckConstraint('length(trim(short_name)) > 0 OR length(trim(long_name)) > 0', name='ck_mpk_routes_name'),
    sa.CheckConstraint('route_type >= 0', name='ck_mpk_routes_type'),
    sa.PrimaryKeyConstraint('source', 'route_id')
    )
    # ### end Alembic commands ###
    op.execute("ALTER TABLE public.mpk_routes ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mpk_routes')
    # ### end Alembic commands ###
