"""create mpk stops

Revision ID: f7fb62616c4c
Revises: 
Create Date: 2026-09-30 19:17:36.100544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7fb62616c4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpk_stops',
    sa.Column('source', sa.String(length=1), nullable=False),
    sa.Column('stop_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.CheckConstraint("source IN ('A', 'T')", name='ck_mpk_stops_source'),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='ck_mpk_stops_latitude'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='ck_mpk_stops_longitude'),
    sa.PrimaryKeyConstraint('source', 'stop_id')
    )
    op.execute(
        "ALTER TABLE public.mpk_stops ENABLE ROW LEVEL SECURITY"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mpk_stops')
    # ### end Alembic commands ###
